### ISSUE TITLE
Is "32 bit timescales are preferable for installed-base of browsers" still valid?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Guidelines-TimingModel#29]
IOP v4.3 section 4.4.3.1 contains the sentence fragment "32 bit timescales are preferable for installed-base of browsers."

My knowledge of browser internals is small but is this still a relevant concern in 2019? If not, I propose we remove this statement. @epiclabsDASH can you comment?

**Comment by sandersaares** [comment]
No longer present in timing model text that references timescales.

**Comment by TobbeEdgeware** [comment]
I'm not sure it is relevant here but there is the Javascript MAX_SAFE_INTEGER = 2^53 -1 due to all Javascript numbers being represented as double. This leads to overflow in timestamps for example if AST=1970-01-01 is used together with the default Smooth Streaming timescale of 10,000,000 ticks/second.

**Comment by sandersaares** [comment]
That's true. There's a statement in the timing model text that says timestamps should be kept under the 2^53 limit. There is also an example about the 90 KHz timescale saying it is no problem. I will also add an example for the Smooth Streaming timescale to point out that common source of problems!
