### ISSUE TITLE
interoperability

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Guidelines-TimingModel#34]
Please outline the differences compared to version N-1 and where interop is broken. Updating versions and breaking compatibility to a N-1 seems odd. 
for a reader/implementor it would be useful to know:
- why interop is broken with prior version
- what the differences are with the prior version

**Comment by sandersaares** [comment]
It is not clear to me what you refer to here.

Do you refer to the general statement in the text? Focusing on the here and now is certainly intentional - DASH-IF guidelines exist to document the interoperable reality as it exists. We publish guidelines for people implementing solutions today. Descriptions and connections to non-interoperable mechanisms are strictly a "nice to have" level goal, as we need to conserve the time and attention of contributors.

Or do you refer to some specific breaking change you would like to see better explained?

**Comment by RufaelDev** [comment]
It would be good to document the differences and why these differences are in het new version breaking interoperability. The text explicitly mentions differences and breaking changes compared to prior version but they are not documented

**Comment by sandersaares** [comment]
That is a general statement that there may be breaking changes.

As the previous version of IOP did not include any meaningful timing model, I suppose the breaking change is the very fact that a timing model is now described. The impact of this is outlined in the timing model into and I imagine will also be in the v5 master changelog. Does that satisfy your request for breaking change clarification?

**Comment by sandersaares** [comment]
Proposed resolution: close the issue.

Rationale: introduction of the chapter outlines what is the breaking change; for sure it will also be covered in the v5 master changelog.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No comments received
