### ISSUE TITLE
Periods (5.3.)

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Guidelines-TimingModel#37]
- please elaborate on the use of zero duration periods
- timing examples may help and more exact definition of the timing behavior in differnt cases (unknown duration period, updated period, fixed duration period etc.)
- consider merging with section 5.8

**Comment by sandersaares** [comment]
> please elaborate on the use of zero duration periods

Changed this to SHALL NOT have a duration of zero. This was some legacy leftover because old IOP versions allowed it but there were already comments questioning this and there's really no justification besides "for legacy reasons", so we might as well say don't do this.

> timing examples may help and more exact definition of the timing behavior in differnt cases (unknown duration period, updated period, fixed duration period etc.)

Chapters "Presentation timing characteristics" and "First and last period timing in dynamic/static presentations" created to try better clarify this. I think it could be further improved but currently lack the inspiration as to how.

In some sense, perfect definitions are not practical as many of the components are defined in referenced specifications like DASH and there is also a stylistic choice to make the document as one intended to be consumed as a whole - there's a concept introduced in e.g. "Period timing" and then futher chapters explain how other elements relate to it. That is, it is explicitly not a goal that anyone can go to "Period" chapter and know all about period timing. That chapter just introduces the period timing aspect, further elaborated throughout the text.

> consider merging with section 5.8

Structure adjusted somewhat, though not merged these. What do you think of the latest draft?

**Comment by sandersaares** [comment]
Proposed resolution: close issue; appropriate clarifications were made to text.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No comments received. Issue is closed
