### ISSUE TITLE
Web documentation is down

### ISSUE THREAD

**Issue by jbree** [Dash-Industry-Forum/Guidelines-TimingModel#63]
When visiting HTML documentation:
https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html

Error 403 - This web app is stopped.

![image](https://github.com/user-attachments/assets/ac06fc16-8fe3-4933-b990-36b6d8dd2dfc)

**Comment by 3052** [comment]
wow that is really annoying - and no mirrors that I can see - as a workaround you can look at the source itself:
https://github.com/Dash-Industry-Forum/Guidelines-TimingModel/blob/master/21-Timing.inc.md

**Comment by stevemayhew** [comment]
@haudiobe  Can I help out with this?   @jbree I suspect the disruption is from the acquisition of DASH-IF by SCTA:  https://dashif.org/news/svta/

Seems a GitHub action like autodoc could build and produce tagged releases of the guidelines on a GitHub.io subdomain.  GitHub hosts this for nothing.

**Comment by thasso** [comment]
I will move this to the new publishing workflow asap. Will take a few more days though since I'm traveling this week.

Note that the new URLs might not end up to be 100%. We are discussing right now what the best result would be for permanent and stable URLs and files.
But at least the html version should be available again soon.

**Comment by thasso** [comment]
The repo is ported to the new publishing workflow and the documents are available at:

https://dashif.org/Guidelines-TimingModel/ for the HTML version and https://dashif.org/Guidelines-TimingModel/Timing-Model.pdf for the PDF. The links in the readme are also updated accordingly.
